### ISSUE TITLE
ISO install on VirtualBox for Vagrant stopped working from Big-IP 14.1 onwards

### ISSUE THREAD

**Issue by boeboe** [f5devcentral/f5-vagrant-files#3]
<img width="982" alt="Screen Shot 2020-01-19 at 21 55 44" src="https://user-images.githubusercontent.com/415310/72688671-c7242280-3b09-11ea-9e50-e1e8622b82ff.png">

Hi,

I used to be able to create Vagrant boxes for KVM and Virtualbox, by using the official iso install images on downloads.f5.com. However, from Big-IP v14.1 onwards, the installation process does not bootstrap anymore (see screenshot above). Is this because Virtualbox is no longer supported inside those iso installation disks?

Best regards,
Bart

**Comment by adam-f5** [comment]
Repository Archived
